### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by Vitoshka** [WoWruRU-ClassicAddons/CritLine#1]
Возникают разные ошибки, каждый раз когда фиксируется новый рекорд... 

[2018/10/06 21:34:31-3286-x1]: CritLine\CritLine.lua:506: attempt to call global `COLOR' (a string value)
CritLine\CritLine.lua:506: in function `CritLine_Init'
CritLine\CritLine.lua:36: in function `CritLine_OnEvent'
<string>:"CritLineFrameMini:OnEvent":2: in main chunk

  ---

[2018/10/06 21:34:36-3286-x1]: CritLine\CritLine.lua:506: attempt to call global `COLOR' (a string value)
CritLine\CritLine.lua:506: in function `CritLine_Init'
CritLine\CritLine.lua:50: in function `CritLine_OnEvent'
<string>:"CritLineFrameMini:OnEvent":2: in main chunk

  ---

[2018/10/06 21:35:22-3286-x7]: CritLine\CritLine.lua:330: attempt to call global `COLOR' (a string value)
CritLine\CritLine.lua:330: in function `CritLine_GetSummaryRichText'
CritLine\CritLine.lua:244: in function `CritLine_RecordHit'
CritLine\CritLine.lua:79: in function `CritLine_OnEvent'
<string>:"CritLineFrameMini:OnEvent":2: in main chunk

  ---

[2018/10/06 21:36:13-3286-x2]: CritLine\CritLine.lua:330: attempt to call global `COLOR' (a string value)
CritLine\CritLine.lua:330: in function `CritLine_GetSummaryRichText'
CritLine\CritLine.lua:244: in function `CritLine_RecordHit'
CritLine\CritLine.lua:67: in function `CritLine_OnEvent'
<string>:"CritLineFrameMini:OnEvent":2: in main chunk

  ---

**Comment by Artur91425** [comment]
Протестировал, ошибок нет. Возможно конфликт с другим аддоном. Какие аддоны используются совместно?

**Comment by Vitoshka** [comment]
Возможен конфликт с [ColorSocialFrame](https://github.com/Road-block/ColorSocialFrame)

**Comment by Artur91425** [comment]
Обновил перевод и переименовал функцию COLOR. По идеи это должно помочь.

**Comment by Vitoshka** [comment]
Всё работает отлично. Маленькая просьба, а может есть возможность сделать FuBar плагин для данного аддона?

**Comment by Artur91425** [comment]
ну... при желании конечно возможно...
Короче, если будет время, то сделаю, но нужно подробно описать, что конкретно там должно быть, какие пункт меню или в подсказке какие данные вводить.
И пожалуйста пиши мне в ВК, так проще и быстрее будет. https://vk.com/id65515748
